<?php

/**
 * Field blueprint for NPPC-LAB-FRM-001.
 * Captured from Form Designer ACTIVE revision 04
 * via `php artisan controlled-forms:export-blueprints`.
 */

return array (
  'page' => 
  array (
    'width' => 215.9,
    'height' => 355.6,
    'unit' => 'mm',
  ),
  'fields' => 
  array (
    0 => 
    array (
      'name' => 'reference_no',
      'label' => 'Reference No',
      'type' => 'text',
      'page' => 1,
      'x' => 160.0,
      'y' => 34.644,
      'w' => 38.0,
      'h' => 5.0,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.reference_no',
    ),
    1 => 
    array (
      'name' => 'customer_name',
      'label' => 'Customer Name',
      'type' => 'text',
      'page' => 1,
      'x' => 29.75,
      'y' => 34.644,
      'w' => 100.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.customer_name',
    ),
    2 => 
    array (
      'name' => 'address',
      'label' => 'Address',
      'type' => 'text',
      'page' => 1,
      'x' => 29.75,
      'y' => 39.144,
      'w' => 105.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.customer_address',
    ),
    3 => 
    array (
      'name' => 'contact_no',
      'label' => 'Contact No',
      'type' => 'text',
      'page' => 1,
      'x' => 158.75,
      'y' => 39.03,
      'w' => 30.5,
      'h' => 5.0,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.customer_contact',
    ),
    4 => 
    array (
      'name' => 'time_date_submitted',
      'label' => 'Time Date Submitted',
      'type' => 'text',
      'page' => 1,
      'x' => 158.5,
      'y' => 43.49,
      'w' => 43.0,
      'h' => 5.0,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.created_at',
    ),
    5 => 
    array (
      'name' => 'sampling_date',
      'label' => 'Sampling Date',
      'type' => 'text',
      'page' => 1,
      'x' => 37.25,
      'y' => 48.49,
      'w' => 17.0,
      'h' => 4.5,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.sampling_date',
    ),
    6 => 
    array (
      'name' => 'sampling_time',
      'label' => 'Sampling Time',
      'type' => 'text',
      'page' => 1,
      'x' => 79.75,
      'y' => 48.49,
      'w' => 15.375,
      'h' => 5.0,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'job_orders.sampling_time',
    ),
    7 => 
    array (
      'name' => 'sample_collected_by',
      'label' => 'Sample Collected By',
      'type' => 'text',
      'page' => 1,
      'x' => 173.25,
      'y' => 48.49,
      'w' => 30.5,
      'h' => 4.5,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.sample_collected_by',
    ),
    8 => 
    array (
      'name' => 'ownership_private',
      'label' => 'Ownership Private',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 45.25,
      'y' => 44.49,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.ownership_type:private',
    ),
    9 => 
    array (
      'name' => 'ownership_commercial',
      'label' => 'Ownership Commercial',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 63.0,
      'y' => 44.49,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.ownership_type:commercial',
    ),
    10 => 
    array (
      'name' => 'ownership_public',
      'label' => 'Ownership Public',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 88.25,
      'y' => 44.49,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.ownership_type:public',
    ),
    11 => 
    array (
      'name' => 'class_aqua',
      'label' => 'Class Aqua',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 49.25,
      'y' => 53.49,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.classification:aqua',
    ),
    12 => 
    array (
      'name' => 'class_potability',
      'label' => 'Class Potability',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 68.0,
      'y' => 53.49,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.classification:potability',
    ),
    13 => 
    array (
      'name' => 'class_wastewater',
      'label' => 'Class Wastewater',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 92.5,
      'y' => 53.49,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.classification:wastewater',
    ),
    14 => 
    array (
      'name' => 'class_agriculture',
      'label' => 'Class Agriculture',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 118.375,
      'y' => 53.49,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.classification:agriculture',
    ),
    15 => 
    array (
      'name' => 'class_academic',
      'label' => 'Class Academic',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 144.5,
      'y' => 53.49,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.classification:academic',
    ),
    16 => 
    array (
      'name' => 'class_others',
      'label' => 'Class Others',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 49.25,
      'y' => 57.99,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.classification:other',
    ),
    17 => 
    array (
      'name' => 'class_others_text',
      'label' => 'Class Others Text',
      'type' => 'text',
      'page' => 1,
      'x' => 88.25,
      'y' => 56.99,
      'w' => 55.0,
      'h' => 5.0,
      'font_size' => 9.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'class_others_text',
    ),
    18 => 
    array (
      'name' => 'sample_code_1',
      'label' => 'Sample Code 1',
      'type' => 'text',
      'page' => 1,
      'x' => 14.75,
      'y' => 66.304,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_1',
    ),
    19 => 
    array (
      'name' => 'control_number_1',
      'label' => 'Control Number 1',
      'type' => 'text',
      'page' => 1,
      'x' => 74.75,
      'y' => 66.304,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_1',
    ),
    20 => 
    array (
      'name' => 'sample_code_2',
      'label' => 'Sample Code 2',
      'type' => 'text',
      'page' => 1,
      'x' => 14.75,
      'y' => 70.65,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_2',
    ),
    21 => 
    array (
      'name' => 'control_number_2',
      'label' => 'Control Number 2',
      'type' => 'text',
      'page' => 1,
      'x' => 74.75,
      'y' => 70.65,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_2',
    ),
    22 => 
    array (
      'name' => 'sample_code_3',
      'label' => 'Sample Code 3',
      'type' => 'text',
      'page' => 1,
      'x' => 14.75,
      'y' => 75.073,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_3',
    ),
    23 => 
    array (
      'name' => 'control_number_3',
      'label' => 'Control Number 3',
      'type' => 'text',
      'page' => 1,
      'x' => 74.75,
      'y' => 75.073,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_3',
    ),
    24 => 
    array (
      'name' => 'sample_code_4',
      'label' => 'Sample Code 4',
      'type' => 'text',
      'page' => 1,
      'x' => 14.75,
      'y' => 79.301,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_4',
    ),
    25 => 
    array (
      'name' => 'control_number_4',
      'label' => 'Control Number 4',
      'type' => 'text',
      'page' => 1,
      'x' => 74.75,
      'y' => 79.919,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_4',
    ),
    26 => 
    array (
      'name' => 'sample_code_5',
      'label' => 'Sample Code 5',
      'type' => 'text',
      'page' => 1,
      'x' => 14.75,
      'y' => 83.718,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_5',
    ),
    27 => 
    array (
      'name' => 'control_number_5',
      'label' => 'Control Number 5',
      'type' => 'text',
      'page' => 1,
      'x' => 74.75,
      'y' => 83.718,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_5',
    ),
    28 => 
    array (
      'name' => 'sample_code_6',
      'label' => 'Sample Code 6',
      'type' => 'text',
      'page' => 1,
      'x' => 14.75,
      'y' => 88.564,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_6',
    ),
    29 => 
    array (
      'name' => 'control_number_6',
      'label' => 'Control Number 6',
      'type' => 'text',
      'page' => 1,
      'x' => 74.75,
      'y' => 87.993,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_6',
    ),
    30 => 
    array (
      'name' => 'sample_code_7',
      'label' => 'Sample Code 7',
      'type' => 'text',
      'page' => 1,
      'x' => 14.75,
      'y' => 92.91,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_7',
    ),
    31 => 
    array (
      'name' => 'control_number_7',
      'label' => 'Control Number 7',
      'type' => 'text',
      'page' => 1,
      'x' => 74.75,
      'y' => 92.839,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_7',
    ),
    32 => 
    array (
      'name' => 'sample_code_8',
      'label' => 'RFA sample line 8',
      'type' => 'text',
      'page' => 1,
      'x' => 14.5,
      'y' => 97.185,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_8',
    ),
    33 => 
    array (
      'name' => 'control_number_8',
      'label' => 'RFA control number line 8',
      'type' => 'text',
      'page' => 1,
      'x' => 74.75,
      'y' => 97.151,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_8',
    ),
    34 => 
    array (
      'name' => 'sample_code_9',
      'label' => 'RFA sample line 9',
      'type' => 'text',
      'page' => 1,
      'x' => 108.5,
      'y' => 65.622,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_9',
    ),
    35 => 
    array (
      'name' => 'control_number_9',
      'label' => 'RFA control number line 9',
      'type' => 'text',
      'page' => 1,
      'x' => 166.5,
      'y' => 65.122,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_9',
    ),
    36 => 
    array (
      'name' => 'potability_sterile',
      'label' => 'Potability Sterile',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 50.5,
      'y' => 104.255,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.field_data:sterile_bottle',
    ),
    37 => 
    array (
      'name' => 'sample_storage_temp',
      'label' => 'Sample Storage Temp',
      'type' => 'text',
      'page' => 1,
      'x' => 92.75,
      'y' => 102.755,
      'w' => 7.194,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_storage_temp',
    ),
    38 => 
    array (
      'name' => 'ww_local_district',
      'label' => 'Ww Local District',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 13.25,
      'y' => 111.334,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.wastewater_source:district',
    ),
    39 => 
    array (
      'name' => 'ww_faucet',
      'label' => 'Ww Faucet',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 47.0,
      'y' => 111.834,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.wastewater_source:faucet',
    ),
    40 => 
    array (
      'name' => 'ww_tank',
      'label' => 'Ww Tank',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 13.5,
      'y' => 115.834,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.wastewater_source:tank',
    ),
    41 => 
    array (
      'name' => 'ww_deepwell',
      'label' => 'Ww Deepwell',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 47.0,
      'y' => 115.834,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.wastewater_source:deepwell',
    ),
    42 => 
    array (
      'name' => 'ww_others',
      'label' => 'Ww Others',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 69.25,
      'y' => 112.084,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'ww_others',
    ),
    43 => 
    array (
      'name' => 'ww_others_text',
      'label' => 'Ww Others Text',
      'type' => 'text',
      'page' => 1,
      'x' => 74.75,
      'y' => 114.834,
      'w' => 17.0,
      'h' => 4.5,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'ww_others_text',
    ),
    44 => 
    array (
      'name' => 'sampling_site',
      'label' => 'Sampling Site',
      'type' => 'text',
      'page' => 1,
      'x' => 115.75,
      'y' => 48.79,
      'w' => 23.0,
      'h' => 4.5,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.sampling_site',
    ),
    45 => 
    array (
      'name' => 'other_tests',
      'label' => 'Other Tests',
      'type' => 'text',
      'page' => 1,
      'x' => 32.5,
      'y' => 170.147,
      'w' => 162.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.other_tests',
    ),
    46 => 
    array (
      'name' => 'payment_cash',
      'label' => 'Payment Cash',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 36.0,
      'y' => 272.45,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.payment_mode:cash',
    ),
    47 => 
    array (
      'name' => 'payment_billing_partial',
      'label' => 'Payment Billing Partial',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 48.0,
      'y' => 272.45,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.payment_mode:billing_partial',
    ),
    48 => 
    array (
      'name' => 'payment_check',
      'label' => 'Payment Check',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 73.5,
      'y' => 272.45,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.payment_mode:check',
    ),
    49 => 
    array (
      'name' => 'payment_terms_15',
      'label' => 'Payment Terms 15',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 149.75,
      'y' => 272.45,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.payment_terms:15_days',
    ),
    50 => 
    array (
      'name' => 'payment_terms_30',
      'label' => 'Payment Terms 30',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 167.25,
      'y' => 272.45,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.payment_terms:30_days',
    ),
    51 => 
    array (
      'name' => 'billing_total',
      'label' => 'Billing Total',
      'type' => 'text',
      'page' => 1,
      'x' => 73.625,
      'y' => 264.027,
      'w' => 30.125,
      'h' => 3.5,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'billing_total',
    ),
    52 => 
    array (
      'name' => 'conforme_name',
      'label' => 'Conforme Name',
      'type' => 'text',
      'page' => 1,
      'x' => 37.159,
      'y' => 279.373,
      'w' => 59.188,
      'h' => 5.0,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'job_orders.customer_name',
    ),
    53 => 
    array (
      'name' => 'conforme_date',
      'label' => 'Conforme Date',
      'type' => 'text',
      'page' => 1,
      'x' => 136.0,
      'y' => 279.373,
      'w' => 37.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'conforme_date',
    ),
    54 => 
    array (
      'name' => 'received_date',
      'label' => 'Received Date',
      'type' => 'text',
      'page' => 1,
      'x' => 136.5,
      'y' => 289.361,
      'w' => 37.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'job_orders.received_at',
    ),
    55 => 
    array (
      'name' => 'reviewed_date',
      'label' => 'Reviewed Date',
      'type' => 'text',
      'page' => 1,
      'x' => 136.5,
      'y' => 299.413,
      'w' => 37.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'job_orders.jo_approved_at',
    ),
    56 => 
    array (
      'name' => 'bill_param_1',
      'label' => 'Bill Param 1',
      'type' => 'text',
      'page' => 1,
      'x' => 13.75,
      'y' => 219.064,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_1',
    ),
    57 => 
    array (
      'name' => 'bill_price_1',
      'label' => 'Bill Price 1',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 219.064,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_1',
    ),
    58 => 
    array (
      'name' => 'bill_total_1',
      'label' => 'Bill Total 1',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 219.064,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_1',
    ),
    59 => 
    array (
      'name' => 'bill_param_2',
      'label' => 'Bill Param 2',
      'type' => 'text',
      'page' => 1,
      'x' => 13.75,
      'y' => 222.994,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_2',
    ),
    60 => 
    array (
      'name' => 'bill_price_2',
      'label' => 'Bill Price 2',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 222.994,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_2',
    ),
    61 => 
    array (
      'name' => 'bill_total_2',
      'label' => 'Bill Total 2',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 222.994,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_2',
    ),
    62 => 
    array (
      'name' => 'bill_param_3',
      'label' => 'Bill Param 3',
      'type' => 'text',
      'page' => 1,
      'x' => 13.75,
      'y' => 227.84,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_3',
    ),
    63 => 
    array (
      'name' => 'bill_price_3',
      'label' => 'Bill Price 3',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 227.84,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_3',
    ),
    64 => 
    array (
      'name' => 'bill_total_3',
      'label' => 'Bill Total 3',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 227.84,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_3',
    ),
    65 => 
    array (
      'name' => 'bill_param_4',
      'label' => 'Bill Param 4',
      'type' => 'text',
      'page' => 1,
      'x' => 13.75,
      'y' => 232.26,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_4',
    ),
    66 => 
    array (
      'name' => 'bill_price_4',
      'label' => 'Bill Price 4',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 232.26,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_4',
    ),
    67 => 
    array (
      'name' => 'bill_total_4',
      'label' => 'Bill Total 4',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 232.26,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_4',
    ),
    68 => 
    array (
      'name' => 'bill_param_5',
      'label' => 'Bill Param 5',
      'type' => 'text',
      'page' => 1,
      'x' => 13.75,
      'y' => 236.606,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_5',
    ),
    69 => 
    array (
      'name' => 'bill_price_5',
      'label' => 'Bill Price 5',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 236.606,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_5',
    ),
    70 => 
    array (
      'name' => 'bill_total_5',
      'label' => 'Bill Total 5',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 236.606,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_5',
    ),
    71 => 
    array (
      'name' => 'bill_param_6',
      'label' => 'Bill Param 6',
      'type' => 'text',
      'page' => 1,
      'x' => 13.75,
      'y' => 240.991,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_6',
    ),
    72 => 
    array (
      'name' => 'bill_price_6',
      'label' => 'Bill Price 6',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 240.991,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_6',
    ),
    73 => 
    array (
      'name' => 'bill_total_6',
      'label' => 'Bill Total 6',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 240.991,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_6',
    ),
    74 => 
    array (
      'name' => 'bill_param_7',
      'label' => 'Bill Param 7',
      'type' => 'text',
      'page' => 1,
      'x' => 13.75,
      'y' => 245.837,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_7',
    ),
    75 => 
    array (
      'name' => 'bill_price_7',
      'label' => 'Bill Price 7',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 245.837,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_7',
    ),
    76 => 
    array (
      'name' => 'bill_total_7',
      'label' => 'Bill Total 7',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 245.837,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_7',
    ),
    77 => 
    array (
      'name' => 'bill_param_8',
      'label' => 'Bill Param 8',
      'type' => 'text',
      'page' => 1,
      'x' => 13.75,
      'y' => 249.918,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_8',
    ),
    78 => 
    array (
      'name' => 'bill_price_8',
      'label' => 'Bill Price 8',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 249.918,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_8',
    ),
    79 => 
    array (
      'name' => 'bill_total_8',
      'label' => 'Bill Total 8',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 249.918,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_8',
    ),
    80 => 
    array (
      'name' => 'bill_param_9',
      'label' => 'Bill Param 9',
      'type' => 'text',
      'page' => 1,
      'x' => 13.75,
      'y' => 254.764,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_9',
    ),
    81 => 
    array (
      'name' => 'bill_price_9',
      'label' => 'Bill Price 9',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 254.764,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_9',
    ),
    82 => 
    array (
      'name' => 'bill_total_9',
      'label' => 'Bill Total 9',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 254.764,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_9',
    ),
    83 => 
    array (
      'name' => 'bill_param_10',
      'label' => 'Bill Param 10',
      'type' => 'text',
      'page' => 1,
      'x' => 13.75,
      'y' => 258.681,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_10',
    ),
    84 => 
    array (
      'name' => 'bill_price_10',
      'label' => 'Bill Price 10',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 258.681,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_10',
    ),
    85 => 
    array (
      'name' => 'bill_total_10',
      'label' => 'Bill Total 10',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 258.681,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_10',
    ),
    86 => 
    array (
      'name' => 'bill_param_11',
      'label' => 'Billing parameter 11',
      'type' => 'text',
      'page' => 1,
      'x' => 109.75,
      'y' => 219.064,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_11',
    ),
    87 => 
    array (
      'name' => 'bill_price_11',
      'label' => 'Billing price 11',
      'type' => 'text',
      'page' => 1,
      'x' => 160.25,
      'y' => 219.064,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_11',
    ),
    88 => 
    array (
      'name' => 'bill_total_11',
      'label' => 'Billing line total 11',
      'type' => 'text',
      'page' => 1,
      'x' => 180.25,
      'y' => 219.064,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_11',
    ),
    89 => 
    array (
      'name' => 'bill_param_12',
      'label' => 'Billing parameter 12',
      'type' => 'text',
      'page' => 1,
      'x' => 109.75,
      'y' => 222.994,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_12',
    ),
    90 => 
    array (
      'name' => 'bill_price_12',
      'label' => 'Billing price 12',
      'type' => 'text',
      'page' => 1,
      'x' => 160.25,
      'y' => 222.994,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_12',
    ),
    91 => 
    array (
      'name' => 'bill_total_12',
      'label' => 'Billing line total 12',
      'type' => 'text',
      'page' => 1,
      'x' => 180.25,
      'y' => 222.994,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_12',
    ),
    92 => 
    array (
      'name' => 'bill_param_13',
      'label' => 'Billing parameter 13',
      'type' => 'text',
      'page' => 1,
      'x' => 109.75,
      'y' => 227.84,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_13',
    ),
    93 => 
    array (
      'name' => 'bill_price_13',
      'label' => 'Billing price 13',
      'type' => 'text',
      'page' => 1,
      'x' => 160.25,
      'y' => 227.84,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_13',
    ),
    94 => 
    array (
      'name' => 'bill_total_13',
      'label' => 'Billing line total 13',
      'type' => 'text',
      'page' => 1,
      'x' => 180.25,
      'y' => 227.84,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_13',
    ),
    95 => 
    array (
      'name' => 'bill_param_14',
      'label' => 'Billing parameter 14',
      'type' => 'text',
      'page' => 1,
      'x' => 109.75,
      'y' => 232.26,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_14',
    ),
    96 => 
    array (
      'name' => 'bill_price_14',
      'label' => 'Billing price 14',
      'type' => 'text',
      'page' => 1,
      'x' => 160.25,
      'y' => 232.26,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_14',
    ),
    97 => 
    array (
      'name' => 'bill_total_14',
      'label' => 'Billing line total 14',
      'type' => 'text',
      'page' => 1,
      'x' => 180.25,
      'y' => 232.26,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_14',
    ),
    98 => 
    array (
      'name' => 'billing_total_right',
      'label' => 'Billing total (right)',
      'type' => 'text',
      'page' => 1,
      'x' => 161.0,
      'y' => 263.527,
      'w' => 38.0,
      'h' => 4.0,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'billing_total_right',
    ),
    99 => 
    array (
      'name' => 'bill_param_15',
      'label' => 'Billing parameter 15',
      'type' => 'text',
      'page' => 1,
      'x' => 109.75,
      'y' => 236.606,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_15',
    ),
    100 => 
    array (
      'name' => 'bill_price_15',
      'label' => 'Billing price 15',
      'type' => 'text',
      'page' => 1,
      'x' => 160.25,
      'y' => 236.606,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_15',
    ),
    101 => 
    array (
      'name' => 'bill_total_15',
      'label' => 'Billing line total 15',
      'type' => 'text',
      'page' => 1,
      'x' => 180.25,
      'y' => 236.606,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_15',
    ),
    102 => 
    array (
      'name' => 'bill_param_16',
      'label' => 'Billing parameter 16',
      'type' => 'text',
      'page' => 1,
      'x' => 109.75,
      'y' => 240.991,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_16',
    ),
    103 => 
    array (
      'name' => 'bill_price_16',
      'label' => 'Billing price 16',
      'type' => 'text',
      'page' => 1,
      'x' => 160.25,
      'y' => 240.991,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_16',
    ),
    104 => 
    array (
      'name' => 'bill_total_16',
      'label' => 'Billing line total 16',
      'type' => 'text',
      'page' => 1,
      'x' => 180.25,
      'y' => 240.991,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_16',
    ),
    105 => 
    array (
      'name' => 'bill_param_17',
      'label' => 'Billing parameter 17',
      'type' => 'text',
      'page' => 1,
      'x' => 109.75,
      'y' => 245.837,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_17',
    ),
    106 => 
    array (
      'name' => 'bill_price_17',
      'label' => 'Billing price 17',
      'type' => 'text',
      'page' => 1,
      'x' => 160.25,
      'y' => 245.837,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_17',
    ),
    107 => 
    array (
      'name' => 'bill_total_17',
      'label' => 'Billing line total 17',
      'type' => 'text',
      'page' => 1,
      'x' => 180.25,
      'y' => 245.837,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_17',
    ),
    108 => 
    array (
      'name' => 'bill_param_18',
      'label' => 'Billing parameter 18',
      'type' => 'text',
      'page' => 1,
      'x' => 109.75,
      'y' => 249.918,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_18',
    ),
    109 => 
    array (
      'name' => 'bill_price_18',
      'label' => 'Billing price 18',
      'type' => 'text',
      'page' => 1,
      'x' => 160.25,
      'y' => 249.918,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_18',
    ),
    110 => 
    array (
      'name' => 'bill_total_18',
      'label' => 'Billing line total 18',
      'type' => 'text',
      'page' => 1,
      'x' => 180.25,
      'y' => 249.918,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_18',
    ),
    111 => 
    array (
      'name' => 'bill_param_19',
      'label' => 'Billing parameter 19',
      'type' => 'text',
      'page' => 1,
      'x' => 109.75,
      'y' => 254.764,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_19',
    ),
    112 => 
    array (
      'name' => 'bill_price_19',
      'label' => 'Billing price 19',
      'type' => 'text',
      'page' => 1,
      'x' => 160.25,
      'y' => 254.764,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_19',
    ),
    113 => 
    array (
      'name' => 'bill_total_19',
      'label' => 'Billing line total 19',
      'type' => 'text',
      'page' => 1,
      'x' => 180.25,
      'y' => 254.764,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_19',
    ),
    114 => 
    array (
      'name' => 'bill_param_20',
      'label' => 'Billing parameter 20',
      'type' => 'text',
      'page' => 1,
      'x' => 109.75,
      'y' => 258.681,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_20',
    ),
    115 => 
    array (
      'name' => 'bill_price_20',
      'label' => 'Billing price 20',
      'type' => 'text',
      'page' => 1,
      'x' => 160.25,
      'y' => 258.681,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_20',
    ),
    116 => 
    array (
      'name' => 'bill_total_20',
      'label' => 'Billing line total 20',
      'type' => 'text',
      'page' => 1,
      'x' => 180.25,
      'y' => 258.681,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_20',
    ),
    117 => 
    array (
      'name' => 'sample_code_10',
      'label' => 'RFA sample line 10',
      'type' => 'text',
      'page' => 1,
      'x' => 108.5,
      'y' => 70.468,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_10',
    ),
    118 => 
    array (
      'name' => 'control_number_10',
      'label' => 'RFA control number line 10',
      'type' => 'text',
      'page' => 1,
      'x' => 166.5,
      'y' => 69.968,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_10',
    ),
    119 => 
    array (
      'name' => 'sample_code_11',
      'label' => 'RFA sample line 11',
      'type' => 'text',
      'page' => 1,
      'x' => 108.5,
      'y' => 74.391,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_11',
    ),
    120 => 
    array (
      'name' => 'control_number_11',
      'label' => 'RFA control number line 11',
      'type' => 'text',
      'page' => 1,
      'x' => 166.5,
      'y' => 73.891,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_11',
    ),
    121 => 
    array (
      'name' => 'sample_code_12',
      'label' => 'RFA sample line 12',
      'type' => 'text',
      'page' => 1,
      'x' => 108.5,
      'y' => 78.737,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_12',
    ),
    122 => 
    array (
      'name' => 'control_number_12',
      'label' => 'RFA control number line 12',
      'type' => 'text',
      'page' => 1,
      'x' => 166.5,
      'y' => 78.237,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_12',
    ),
    123 => 
    array (
      'name' => 'sample_code_13',
      'label' => 'RFA sample line 13',
      'type' => 'text',
      'page' => 1,
      'x' => 108.5,
      'y' => 83.542,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_13',
    ),
    124 => 
    array (
      'name' => 'control_number_13',
      'label' => 'RFA control number line 13',
      'type' => 'text',
      'page' => 1,
      'x' => 166.5,
      'y' => 83.042,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_13',
    ),
    125 => 
    array (
      'name' => 'sample_code_14',
      'label' => 'RFA sample line 14',
      'type' => 'text',
      'page' => 1,
      'x' => 108.5,
      'y' => 87.882,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_14',
    ),
    126 => 
    array (
      'name' => 'control_number_14',
      'label' => 'RFA control number line 14',
      'type' => 'text',
      'page' => 1,
      'x' => 166.5,
      'y' => 87.382,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_14',
    ),
    127 => 
    array (
      'name' => 'sample_code_15',
      'label' => 'RFA sample line 15',
      'type' => 'text',
      'page' => 1,
      'x' => 108.5,
      'y' => 92.728,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_15',
    ),
    128 => 
    array (
      'name' => 'control_number_15',
      'label' => 'RFA control number line 15',
      'type' => 'text',
      'page' => 1,
      'x' => 166.5,
      'y' => 92.228,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_15',
    ),
    129 => 
    array (
      'name' => 'sample_code_16',
      'label' => 'RFA sample line 16',
      'type' => 'text',
      'page' => 1,
      'x' => 108.5,
      'y' => 97.256,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_16',
    ),
    130 => 
    array (
      'name' => 'control_number_16',
      'label' => 'RFA control number line 16',
      'type' => 'text',
      'page' => 1,
      'x' => 166.5,
      'y' => 97.074,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_16',
    ),
  ),
);
