<?php

/**
 * Field blueprint for NPPC-LAB-FRM-AQUA.
 * Captured from Form Designer ACTIVE revision 01
 * via `php artisan controlled-forms:export-blueprints`.
 */

return array (
  'page' => 
  array (
    'width' => 215.9,
    'height' => 355.6,
    'unit' => 'mm',
  ),
  'fields' => 
  array (
    0 => 
    array (
      'name' => 'reference_no',
      'label' => 'Reference No',
      'type' => 'text',
      'page' => 1,
      'x' => 159.75,
      'y' => 46.927,
      'w' => 38.0,
      'h' => 5.0,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.reference_no',
    ),
    1 => 
    array (
      'name' => 'customer_name',
      'label' => 'Customer Name',
      'type' => 'text',
      'page' => 1,
      'x' => 24.25,
      'y' => 46.927,
      'w' => 100.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.customer_name',
    ),
    2 => 
    array (
      'name' => 'address',
      'label' => 'Address',
      'type' => 'text',
      'page' => 1,
      'x' => 26.25,
      'y' => 51.387,
      'w' => 105.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.customer_address',
    ),
    3 => 
    array (
      'name' => 'contact_no',
      'label' => 'Contact No',
      'type' => 'text',
      'page' => 1,
      'x' => 157.25,
      'y' => 51.273,
      'w' => 30.5,
      'h' => 5.0,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.customer_contact',
    ),
    4 => 
    array (
      'name' => 'time_date_submitted',
      'label' => 'Time Date Submitted',
      'type' => 'text',
      'page' => 1,
      'x' => 151.25,
      'y' => 55.733,
      'w' => 43.0,
      'h' => 5.0,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.created_at',
    ),
    5 => 
    array (
      'name' => 'sample_collected_by',
      'label' => 'Sample Collected By',
      'type' => 'text',
      'page' => 1,
      'x' => 124.25,
      'y' => 60.273,
      'w' => 63.75,
      'h' => 5.0,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.sample_collected_by',
    ),
    6 => 
    array (
      'name' => 'ownership_private',
      'label' => 'Ownership Private',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 44.75,
      'y' => 56.733,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.ownership_type:private',
    ),
    7 => 
    array (
      'name' => 'ownership_commercial',
      'label' => 'Ownership Commercial',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 62.25,
      'y' => 56.773,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.ownership_type:commercial',
    ),
    8 => 
    array (
      'name' => 'ownership_public',
      'label' => 'Ownership Public',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 86.25,
      'y' => 56.733,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.ownership_type:public',
    ),
    9 => 
    array (
      'name' => 'class_aqua',
      'label' => 'Class Aqua',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 49.75,
      'y' => 65.483,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.classification:aqua',
    ),
    10 => 
    array (
      'name' => 'class_agriculture',
      'label' => 'Class Agriculture',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 68.75,
      'y' => 65.483,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.classification:agriculture',
    ),
    11 => 
    array (
      'name' => 'class_academic',
      'label' => 'Class Academic',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 96.0,
      'y' => 65.233,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.classification:academic',
    ),
    12 => 
    array (
      'name' => 'class_others',
      'label' => 'Class Others',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 132.75,
      'y' => 65.233,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.classification:other',
    ),
    13 => 
    array (
      'name' => 'class_others_text',
      'label' => 'Class Others Text',
      'type' => 'text',
      'page' => 1,
      'x' => 172.5,
      'y' => 64.733,
      'w' => 34.0,
      'h' => 5.0,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'class_others_text',
    ),
    14 => 
    array (
      'name' => 'aqua_sea',
      'label' => 'Aqua Sea',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 13.25,
      'y' => 132.577,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'aqua_sea',
    ),
    15 => 
    array (
      'name' => 'aqua_brackish',
      'label' => 'Aqua Brackish',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 47.0,
      'y' => 132.577,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'aqua_brackish',
    ),
    16 => 
    array (
      'name' => 'aqua_river',
      'label' => 'Aqua River',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 13.5,
      'y' => 137.077,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'aqua_river',
    ),
    17 => 
    array (
      'name' => 'ww_others',
      'label' => 'Ww Others',
      'type' => 'checkbox',
      'page' => 1,
      'x' => 13.5,
      'y' => 140.577,
      'w' => 3.5,
      'h' => 3.5,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'ww_others',
    ),
    18 => 
    array (
      'name' => 'ww_others_text',
      'label' => 'Ww Others Text',
      'type' => 'text',
      'page' => 1,
      'x' => 56.25,
      'y' => 139.327,
      'w' => 17.0,
      'h' => 4.5,
      'font_size' => 9.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'ww_others_text',
    ),
    19 => 
    array (
      'name' => 'other_tests',
      'label' => 'Other Tests',
      'type' => 'text',
      'page' => 1,
      'x' => 33.25,
      'y' => 187.461,
      'w' => 162.0,
      'h' => 4.846,
      'font_size' => 10.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.other_tests',
    ),
    20 => 
    array (
      'name' => 'billing_total',
      'label' => 'Billing Total',
      'type' => 'text',
      'page' => 1,
      'x' => 76.25,
      'y' => 280.77,
      'w' => 30.25,
      'h' => 5.0,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'job_orders.total_cost',
    ),
    21 => 
    array (
      'name' => 'conforme_date',
      'label' => 'Conforme Date',
      'type' => 'text',
      'page' => 1,
      'x' => 136.0,
      'y' => 286.27,
      'w' => 37.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'conforme_date',
    ),
    22 => 
    array (
      'name' => 'received_date',
      'label' => 'Received Date',
      'type' => 'text',
      'page' => 1,
      'x' => 136.25,
      'y' => 296.04,
      'w' => 37.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.received_at',
    ),
    23 => 
    array (
      'name' => 'reviewed_date',
      'label' => 'Reviewed Date',
      'type' => 'text',
      'page' => 1,
      'x' => 136.0,
      'y' => 306.31,
      'w' => 37.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'job_orders.reviewed_at',
    ),
    24 => 
    array (
      'name' => 'sample_code_1',
      'label' => 'Sample Code 1',
      'type' => 'text',
      'page' => 1,
      'x' => 13.0,
      'y' => 78.047,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_1',
    ),
    25 => 
    array (
      'name' => 'control_number_1',
      'label' => 'Control Number 1',
      'type' => 'text',
      'page' => 1,
      'x' => 74.25,
      'y' => 78.047,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_1',
    ),
    26 => 
    array (
      'name' => 'sample_code_2',
      'label' => 'Sample Code 2',
      'type' => 'text',
      'page' => 1,
      'x' => 13.0,
      'y' => 82.893,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_2',
    ),
    27 => 
    array (
      'name' => 'control_number_2',
      'label' => 'Control Number 2',
      'type' => 'text',
      'page' => 1,
      'x' => 74.25,
      'y' => 82.893,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_2',
    ),
    28 => 
    array (
      'name' => 'sample_code_3',
      'label' => 'Sample Code 3',
      'type' => 'text',
      'page' => 1,
      'x' => 13.25,
      'y' => 86.816,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_3',
    ),
    29 => 
    array (
      'name' => 'control_number_3',
      'label' => 'Control Number 3',
      'type' => 'text',
      'page' => 1,
      'x' => 74.25,
      'y' => 86.816,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_3',
    ),
    30 => 
    array (
      'name' => 'sample_code_4',
      'label' => 'Sample Code 4',
      'type' => 'text',
      'page' => 1,
      'x' => 13.25,
      'y' => 91.162,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_4',
    ),
    31 => 
    array (
      'name' => 'control_number_4',
      'label' => 'Control Number 4',
      'type' => 'text',
      'page' => 1,
      'x' => 74.25,
      'y' => 91.662,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_4',
    ),
    32 => 
    array (
      'name' => 'sample_code_5',
      'label' => 'Sample Code 5',
      'type' => 'text',
      'page' => 1,
      'x' => 13.0,
      'y' => 95.467,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_5',
    ),
    33 => 
    array (
      'name' => 'control_number_5',
      'label' => 'Control Number 5',
      'type' => 'text',
      'page' => 1,
      'x' => 74.5,
      'y' => 95.89,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_5',
    ),
    34 => 
    array (
      'name' => 'sample_code_6',
      'label' => 'Sample Code 6',
      'type' => 'text',
      'page' => 1,
      'x' => 12.75,
      'y' => 100.307,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_6',
    ),
    35 => 
    array (
      'name' => 'control_number_6',
      'label' => 'Control Number 6',
      'type' => 'text',
      'page' => 1,
      'x' => 74.25,
      'y' => 100.736,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_6',
    ),
    36 => 
    array (
      'name' => 'sample_code_7',
      'label' => 'Sample Code 7',
      'type' => 'text',
      'page' => 1,
      'x' => 12.75,
      'y' => 105.153,
      'w' => 50.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'sample_code_7',
    ),
    37 => 
    array (
      'name' => 'control_number_7',
      'label' => 'Control Number 7',
      'type' => 'text',
      'page' => 1,
      'x' => 74.75,
      'y' => 105.582,
      'w' => 28.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'control_number_7',
    ),
    38 => 
    array (
      'name' => 'job_orders.sampling_date',
      'label' => 'Sampling Date',
      'type' => 'date',
      'page' => 1,
      'x' => 36.75,
      'y' => 60.233,
      'w' => 17.0,
      'h' => 5.0,
      'font_size' => 9.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'job_orders.sampling_date',
    ),
    39 => 
    array (
      'name' => 'job_orders.sampling_time',
      'label' => 'Sampling Time',
      'type' => 'text',
      'page' => 1,
      'x' => 78.25,
      'y' => 60.233,
      'w' => 12.125,
      'h' => 5.5,
      'font_size' => 9.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'job_orders.sampling_time',
    ),
    40 => 
    array (
      'name' => 'bill_param_1',
      'label' => 'Bill Param 1',
      'type' => 'text',
      'page' => 1,
      'x' => 12.25,
      'y' => 236.307,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_1',
    ),
    41 => 
    array (
      'name' => 'bill_price_1',
      'label' => 'Bill Price 1',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 236.307,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_1',
    ),
    42 => 
    array (
      'name' => 'bill_total_1',
      'label' => 'Bill Total 1',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 236.307,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_1',
    ),
    43 => 
    array (
      'name' => 'bill_param_2',
      'label' => 'Bill Param 2',
      'type' => 'text',
      'page' => 1,
      'x' => 12.25,
      'y' => 240.237,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_2',
    ),
    44 => 
    array (
      'name' => 'bill_price_2',
      'label' => 'Bill Price 2',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 240.237,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_2',
    ),
    45 => 
    array (
      'name' => 'bill_total_2',
      'label' => 'Bill Total 2',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 240.237,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_2',
    ),
    46 => 
    array (
      'name' => 'bill_param_3',
      'label' => 'Bill Param 3',
      'type' => 'text',
      'page' => 1,
      'x' => 12.25,
      'y' => 245.083,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_3',
    ),
    47 => 
    array (
      'name' => 'bill_price_3',
      'label' => 'Bill Price 3',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 245.083,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_3',
    ),
    48 => 
    array (
      'name' => 'bill_total_3',
      'label' => 'Bill Total 3',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 245.083,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_3',
    ),
    49 => 
    array (
      'name' => 'bill_param_4',
      'label' => 'Bill Param 4',
      'type' => 'text',
      'page' => 1,
      'x' => 12.25,
      'y' => 249.503,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_4',
    ),
    50 => 
    array (
      'name' => 'bill_price_4',
      'label' => 'Bill Price 4',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 249.503,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_4',
    ),
    51 => 
    array (
      'name' => 'bill_total_4',
      'label' => 'Bill Total 4',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 249.503,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_4',
    ),
    52 => 
    array (
      'name' => 'bill_param_5',
      'label' => 'Bill Param 5',
      'type' => 'text',
      'page' => 1,
      'x' => 12.25,
      'y' => 253.849,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_5',
    ),
    53 => 
    array (
      'name' => 'bill_price_5',
      'label' => 'Bill Price 5',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 253.849,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_5',
    ),
    54 => 
    array (
      'name' => 'bill_total_5',
      'label' => 'Bill Total 5',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 253.849,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_5',
    ),
    55 => 
    array (
      'name' => 'bill_param_6',
      'label' => 'Bill Param 6',
      'type' => 'text',
      'page' => 1,
      'x' => 12.25,
      'y' => 258.234,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_6',
    ),
    56 => 
    array (
      'name' => 'bill_price_6',
      'label' => 'Bill Price 6',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 258.234,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_6',
    ),
    57 => 
    array (
      'name' => 'bill_total_6',
      'label' => 'Bill Total 6',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 258.234,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_6',
    ),
    58 => 
    array (
      'name' => 'bill_param_7',
      'label' => 'Bill Param 7',
      'type' => 'text',
      'page' => 1,
      'x' => 12.25,
      'y' => 263.08,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_7',
    ),
    59 => 
    array (
      'name' => 'bill_price_7',
      'label' => 'Bill Price 7',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 263.08,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_7',
    ),
    60 => 
    array (
      'name' => 'bill_total_7',
      'label' => 'Bill Total 7',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 263.08,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_7',
    ),
    61 => 
    array (
      'name' => 'bill_param_8',
      'label' => 'Bill Param 8',
      'type' => 'text',
      'page' => 1,
      'x' => 12.25,
      'y' => 267.161,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_8',
    ),
    62 => 
    array (
      'name' => 'bill_price_8',
      'label' => 'Bill Price 8',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 267.161,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_8',
    ),
    63 => 
    array (
      'name' => 'bill_total_8',
      'label' => 'Bill Total 8',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 267.161,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_8',
    ),
    64 => 
    array (
      'name' => 'bill_param_9',
      'label' => 'Bill Param 9',
      'type' => 'text',
      'page' => 1,
      'x' => 12.25,
      'y' => 272.007,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_9',
    ),
    65 => 
    array (
      'name' => 'bill_price_9',
      'label' => 'Bill Price 9',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 271.091,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_9',
    ),
    66 => 
    array (
      'name' => 'bill_total_9',
      'label' => 'Bill Total 9',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 271.091,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_9',
    ),
    67 => 
    array (
      'name' => 'bill_param_10',
      'label' => 'Bill Param 10',
      'type' => 'text',
      'page' => 1,
      'x' => 12.25,
      'y' => 275.924,
      'w' => 43.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'L',
      'data_source_key' => 'bill_param_10',
    ),
    68 => 
    array (
      'name' => 'bill_price_10',
      'label' => 'Bill Price 10',
      'type' => 'text',
      'page' => 1,
      'x' => 64.25,
      'y' => 275.511,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_price_10',
    ),
    69 => 
    array (
      'name' => 'bill_total_10',
      'label' => 'Bill Total 10',
      'type' => 'text',
      'page' => 1,
      'x' => 84.25,
      'y' => 275.511,
      'w' => 18.0,
      'h' => 4.846,
      'font_size' => 11.0,
      'font_family' => 'calibri',
      'font_color' => '#000000',
      'align' => 'C',
      'data_source_key' => 'bill_total_10',
    ),
  ),
);
